### PR TITLE
Added Diego's blog post 2023-09-01-collaborative-coding

### PR DESCRIPTION
**Pull request by diegosiqueir4**
Hello DHtech team,

Following the suggestion of @rlskoeser, I've compiled a short blog post titled "**Collaborative Coding: Pair Programming & Co-authoring Git Commits**" for the DHtech blog.

**Summary**
The post includes:
- Pair Programming and Co-authoring: A Dynamic Duo
- Benefits of Co-authoring and Pair Programming
- How to Co-author Git Commits
- Start Co-authoring and Pair Programming Today!
- Further reading

**Request**
Please review the content and feel free to change, remove, or add **anything** you feel necessary, as well as include yourself as one of the authors.

Thanks in advance!

Cheers,
Diego

### CODE REVIEW

**Comment by rlskoeser** [comment]
@diegosiqueir4 this looks great to me! Thanks for writing it up.

The one resource I am wondering if you want to add how to find your no-reply github email if you prefer to keep your real email address private.  It's sort of documented here, but not sure this is the right link, maybe they've changed their documentation. (There used to be one that said more clearly how to find your noreply email.)  https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#about-commit-email-addresses

**Review by rlskoeser — APPROVED** [review]

**Comment by diegosiqueir4** [comment]
> @diegosiqueir4 this looks great to me! Thanks for writing it up.
> 
> The one resource I am wondering if you want to add how to find your no-reply github email if you prefer to keep your real email address private. It's sort of documented here, but not sure this is the right link, maybe they've changed their documentation. (There used to be one that said more clearly how to find your noreply email.) https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#about-commit-email-addresses

Thanks for the feedback, @rlskoeser!

I'm not sure I understand your comment. Are you suggesting adding the link to the "Further reading" list or asking about my noreply email?

**Comment by rlskoeser** [comment]
> I'm not sure I understand your comment. Are you suggesting adding the link to the "Further reading" list or asking about my noreply email?

Suggesting adding another resource link with a brief note somewhere about email privacy.

**Comment by diegosiqueir4** [comment]
> > I'm not sure I understand your comment. Are you suggesting adding the link to the "Further reading" list or asking about my noreply email?
> 
> Suggesting adding another resource link with a brief note somewhere about email privacy.

Thanks for the suggestion, I've added the link to the further reading list.

**Review by jdamerow — APPROVED** [review]

**Comment by jdamerow** [comment]
Thanks @diegosiqueir4! This is great!

**Comment by diegosiqueir4** [comment]
Thanks @jdamerow and @rlskoeser the review and feedback! The post has now been published :smile::v:

**Pull request merged**
